### ISSUE TITLE
Make CI/CD pipeline

### ISSUE THREAD

**Issue by cookk** [cookk/wayne#17]

**Comment by cookk** [comment]
## 설치
```bash
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum install jenkins
```
## 설정
```bash
vi /etc/sysconfig/jenkins
```
## 서비스 시작/종료
```bash
/etc/init.d/jenkins start
/etc/init.d/jenkins stop
```

**Comment by cookk** [comment]
- Error on 'jenkins start'
```
[ec2-user@ip-172-31-17-61 ~]$ sudo /etc/init.d/jenkins start
Starting Jenkins 9월 14, 2019 12:10:37 오전 Main verifyJavaVersion
심각: Running with Java class version 51, which is older than the Minimum required version 52. See https://jenkins.io/redirect/java-support/
java.lang.UnsupportedClassVersionError: 51.0
	at Main.verifyJavaVersion(Main.java:182)
	at Main.main(Main.java:142)

Jenkins requires Java versions [8, 11] but you are running with Java 1.7 from /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.231.x86_64/jre
java.lang.UnsupportedClassVersionError: 51.0
	at Main.verifyJavaVersion(Main.java:182)
	at Main.main(Main.java:142)
                                                           [  OK  ]
```

**Comment by cookk** [comment]
- change jdk 1.7 to 1.8
```bash
sudo yum install -y java-1.8.0-openjdk-devel.x86_64
sudo /usr/sbin/alternatives --config java
sudo yum remove java-1.7.0-openjdk
java -version
```

**Comment by cookk** [comment]
## Setting jenkins server
- Unlock jenkins
```bash
cat /var/lib/jenkins/secrets/initialAdminPassword
```
- Install suggested plugins

**Comment by cookk** [comment]
- Need to install 'git' on jenkins server
```bash
sudo yum install git
```

**Comment by cookk** [comment]
- Build succeeded 😁
```bash
Started by user admin
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/wayne
using credential cookk
Cloning the remote Git repository
Cloning repository https://github.com/cookk/wayne.git
 > git init /var/lib/jenkins/workspace/wayne # timeout=10
Fetching upstream changes from https://github.com/cookk/wayne.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress -- https://github.com/cookk/wayne.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/cookk/wayne.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/cookk/wayne.git # timeout=10
Fetching upstream changes from https://github.com/cookk/wayne.git
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress -- https://github.com/cookk/wayne.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision fa8987fd39f9d5f95f9130c5bf50cb7fd14e036a (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f fa8987fd39f9d5f95f9130c5bf50cb7fd14e036a
Commit message: "Merge pull request #16 from cookk/stage"
First time build. Skipping changelog.
Finished: SUCCESS
```

**Comment by cookk** [comment]
## Change timezone
- You can check timezone at http://[jenkins-server]/systemInfo
- Change jenkins config
```bash
sudo vi /etc/sysconfig/jenkins
```
```
JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Duser.timezone=Asia/Seoul"
```
- Restart jenkins
```bash
sudo /etc/init.d/jenkins stop
sudo /etc/init.d/jenkins start
```

**Comment by cookk** [comment]
- Installed 'Publish Over SSH' plugin with restart option
